# Generated by Django 5.1.7 on 2025-03-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studient_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
