# Generated by Django 5.1.7 on 2025-03-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_studient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
