# Generated by Django 4.2.16 on 2025-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100, verbose_name='留言內容'),
        ),
    ]
